apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: qviewer-config
  labels:
    name: qviewer
  name: qviewer-deploy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: qviewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: qviewer
    spec:
      containers:
      - env:
        - name: STAKATER_JUNIOR_BOT_CONFIG_CONFIGMAP
          value: cb3e75342996ed0d1560c4a4aad32089830f09b6
        envFrom:
        - configMapRef:
            name: qviewer-config
        image: {{IMAGE}}
        imagePullPolicy: Always
        name: qviewer
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
